Repository CS3219-AY2425S1/cs3219-ay2425s1-project-g20, pull requests merged in 2024-10, with the labels that each got.

#38 [Question] Decouple controller, write model component
  .gitignore
  README.md
  common/shared-types/index.ts
  frontend/.gitignore
  pnpm-lock.yaml
  services/question/.gitignore
  services/question/README.md
  services/question/babel.config.js
  services/question/package.json
  services/question/src/__tests__/controller/controller.test.ts
  services/question/src/controller/controller.ts
  services/question/src/controller/questions-controller.ts
  services/question/src/index.ts
  services/question/src/model.ts
  services/question/src/model/collection.ts
  services/question/src/model/model.ts
  services/question/src/routes/questions-routes.ts
  services/question/src/routes/routes.ts
  services/question/src/scripts/upload.ts
  services/question/src/utils/errors.ts
  services/question/src/utils/logger.ts
Labels: discussion

#51 Dockerfile and docker compose
  .dockerignore
  Dockerfile
  common/shared-types/package.json
  common/shared-types/tsconfig.json
  docker-compose.yml
  package.json
  pnpm-lock.yaml
  services/question/package.json
  services/user/package-lock.json
  services/user/package.json
Labels: Devops

#55 Docker compose fixes and JWT secret from a file
  common/shared-types/package.json
  common/shared-types/tsconfig.json
  docker-compose.yml
  jwt_secret.txt
  services/user/src/controller/auth-controller.ts
  services/user/src/middleware/basic-access-control.ts
  services/user/src/utils/jwt-secret.ts
Labels: Bug, critical

#71 Base implementation of matching service
  package.json
  pnpm-lock.yaml
  services/matching/.gitignore
  services/matching/README.md
  services/matching/package.json
  services/matching/src/MatchingServer.ts
  services/matching/src/constants/redis.ts
  services/matching/src/index.ts
  services/matching/src/queue-manager/MatchingQueueManager.ts
  services/matching/src/types/events.ts
  services/matching/src/types/user-data.ts
  services/matching/src/utils/logger.ts
  services/matching/src/utils/ticketid.ts
  services/matching/src/worker/Matcher.ts
  services/matching/tsconfig.json
Labels: HIGH, Backend
